spring.application.name=users

# Puerto
server.port=8082

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/bdUsuarios
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# AWS Cognito
aws.cognito.userPoolId=us-east-1_kACXnAQKt
aws.cognito.clientId=4amlhn4uoo9h719ci4198j6ben